Controller:
  model_structure: null
ReinforcementTrainer:
  controller_learning_rate: 0.1
  controller_optimizer: SGD
  distill_mode: false
  optimizer: SGD
  sentence_level_batch: true
  use_tensorboard: true
embeddings:
  BertEmbeddings-0:
    bert_model_or_path: bert-base-cased
    fine_tune: true
    layers: '-1,-2'
    pooling_operation: mean
  FastWordEmbeddings-0:
    embeddings: glove
    freeze: true
  FlairEmbeddings-0:
    model: en-forward
  FlairEmbeddings-1:
    model: en-backward

interpolation: 0.5
model:
  FastSequenceTagger:
    crf_attention: false
    dropout: 0.0
    hidden_size: 800
    sentence_loss: true
    use_crf: true
model_name: fgcr_ace
ner:
  Corpus: ColumnCorpus-FGCR
  tag_dictionary: resources/taggers/fgcr_tags.pkl
  ColumnCorpus-FGCR:
    data_folder: datasets/fgcr
    column_format:
      0: text
      1: ner
    tag_to_bioes: ner
target_dir: resources/taggers/
targets: ner
train:
  controller_momentum: 0.9
  discount: 0.5
  learning_rate: 0.1
  max_episodes: 30
  max_epochs: 50
  max_epochs_without_improvement: 10
  mini_batch_size: 32
  monitor_test: false
  patience: 5
  save_final_model: false
  train_with_dev: false
  true_reshuffle: false
trainer: ReinforcementTrainer
